// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef _ESP32_2432S028R_UI_H
#define _ESP32_2432S028R_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_MainScreen.h"
#include "ui_SettingScreen.h"
#include "ui_WifiSelectScreen.h"
#include "ui_WifiPasswordScreen.h"
#include "ui_SystemScreen.h"
#include "ui_WeatherScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_settings48px_png);    // assets/settings48px.png
LV_IMG_DECLARE(ui_img_wifi48px_png);    // assets/wifi48px.png
LV_IMG_DECLARE(ui_img_nowifi_14x10_png);    // assets/NoWifi 14x10.png
LV_IMG_DECLARE(ui_img_wifi_14x8_png);    // assets/Wifi 14x8.png
LV_IMG_DECLARE(ui_img_shutdown48px_png);    // assets/shutdown48px.png
LV_IMG_DECLARE(ui_img_system48px_png);    // assets/system48px.png
LV_IMG_DECLARE(ui_img_weather48px_png);    // assets/weather48px.png
LV_IMG_DECLARE(ui_img_correct128px_png);    // assets/correct128px.png
LV_IMG_DECLARE(ui_img_incorrect128px_png);    // assets/incorrect128px.png
LV_IMG_DECLARE(ui_img_icon_temp_22p_png);    // assets/icon_temp_22p.png
LV_IMG_DECLARE(ui_img_icon_max_11p_png);    // assets/icon_max_11p.png
LV_IMG_DECLARE(ui_img_icon_min_11p_png);    // assets/icon_min_11p.png
LV_IMG_DECLARE(ui_img_icon_humd_22p_png);    // assets/icon_humd 22p.png
LV_IMG_DECLARE(ui_img_icon_pressure_11p_png);    // assets/icon_pressure_11p.png
LV_IMG_DECLARE(ui_img_icon_visibility_11p_png);    // assets/icon_visibility_11p.png
LV_IMG_DECLARE(ui_img_icon_wind_11p_png);    // assets/icon_wind_11p.png
LV_IMG_DECLARE(ui_img_icon_location_11p_png);    // assets/icon_location_11p.png
LV_IMG_DECLARE(ui_img_icon_10n_72p_png);    // assets/icon_10n_72p.png
LV_IMG_DECLARE(ui_img_icon_01d_72p_png);    // assets/icon_01d_72p.png
LV_IMG_DECLARE(ui_img_icon_50d_50n_72p_png);    // assets/icon_50d_50n_72p.png
LV_IMG_DECLARE(ui_img_icon_11d_11n_72p_png);    // assets/icon_11d_11n_72p.png
LV_IMG_DECLARE(ui_img_icon_13d_13n_72p_png);    // assets/icon_13d_13n_72p.png
LV_IMG_DECLARE(ui_img_icon_10d_72p_png);    // assets/icon_10d_72p.png
LV_IMG_DECLARE(ui_img_icon_09d_09n_72p_png);    // assets/icon_09d_09n_72p.png
LV_IMG_DECLARE(ui_img_icon_04d_04n_72p_png);    // assets/icon_04d_04n_72p.png
LV_IMG_DECLARE(ui_img_icon_03d_03n_72p_png);    // assets/icon_03d_03n_72p.png
LV_IMG_DECLARE(ui_img_icon_02n_72p_png);    // assets/icon_02n_72p.png
LV_IMG_DECLARE(ui_img_icon_02d_72p_png);    // assets/icon_02d_72p.png
LV_IMG_DECLARE(ui_img_icon_01n_72p_png);    // assets/icon_01n_72p.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
