// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#include "ui.h"

// COMPONENT labelTime

lv_obj_t * ui_labelTime_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_labelTime;
    cui_labelTime = lv_label_create(comp_parent);
    lv_obj_set_width(cui_labelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_labelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_labelTime, 87);
    lv_obj_set_y(cui_labelTime, -12);
    lv_obj_set_align(cui_labelTime, LV_ALIGN_CENTER);
    lv_label_set_text(cui_labelTime, "00:00:00");
    lv_obj_set_style_text_color(cui_labelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_labelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_labelTime, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELTIME_NUM);
    children[UI_COMP_LABELTIME_LABELTIME] = cui_labelTime;
    lv_obj_add_event_cb(cui_labelTime, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_labelTime, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_labelTime_create_hook(cui_labelTime);
    return cui_labelTime;
}

