// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef _UI_COMP_LABELTIME_H
#define _UI_COMP_LABELTIME_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT labelTime
#define UI_COMP_LABELTIME_LABELTIME 0
#define _UI_COMP_LABELTIME_NUM 1
lv_obj_t * ui_labelTime_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
