// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#include "ui.h"

lv_obj_t * ui_MainScreen;
lv_obj_t * ui_labelTime;
lv_obj_t * ui_calendarMonth;
lv_obj_t * ui_labelDate;
lv_obj_t * ui_robotFaceArea;
lv_obj_t * ui_imageRobot;
lv_obj_t * ui_btnSetting;
lv_obj_t * ui_btnWifi;
lv_obj_t * ui_disableWifi;
lv_obj_t * ui_enableWifi;

// event funtions
void ui_event_btnSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_OVER_RIGHT, 50, 0, &ui_SettingScreen_screen_init);
    }
}

void ui_event_btnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiSelectScreen, LV_SCR_LOAD_ANIM_OVER_LEFT, 50, 0, &ui_WifiSelectScreen_screen_init);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MainScreen, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTime = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_labelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTime, 87);
    lv_obj_set_y(ui_labelTime, -9);
    lv_obj_set_align(ui_labelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTime, "--:--:--");
    lv_obj_set_style_text_color(ui_labelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTime, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calendarMonth = lv_calendar_create(ui_MainScreen);
    lv_calendar_set_today_date(ui_calendarMonth, 1900, 1, 1);
    lv_calendar_set_showed_date(ui_calendarMonth, 1900, 1);
    lv_obj_t * ui_calendarMonth_header = lv_calendar_header_arrow_create(ui_calendarMonth);
    lv_obj_set_width(ui_calendarMonth, 174);
    lv_obj_set_height(ui_calendarMonth, 234);
    lv_obj_set_x(ui_calendarMonth, -73);
    lv_obj_set_y(ui_calendarMonth, 1);
    lv_obj_set_align(ui_calendarMonth, LV_ALIGN_CENTER);

    ui_labelDate = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_labelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDate, 86);
    lv_obj_set_y(ui_labelDate, 20);
    lv_obj_set_align(ui_labelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDate, "---, --/--/----");
    lv_obj_set_style_text_color(ui_labelDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_robotFaceArea = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_robotFaceArea);
    lv_obj_set_width(ui_robotFaceArea, 134);
    lv_obj_set_height(ui_robotFaceArea, 70);
    lv_obj_set_x(ui_robotFaceArea, 87);
    lv_obj_set_y(ui_robotFaceArea, -65);
    lv_obj_set_align(ui_robotFaceArea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_robotFaceArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_robotFaceArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_robotFaceArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_robotFaceArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageRobot = lv_img_create(ui_robotFaceArea);
    lv_obj_set_width(ui_imageRobot, 128);
    lv_obj_set_height(ui_imageRobot, 64);
    lv_obj_set_align(ui_imageRobot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageRobot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageRobot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imageRobot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageRobot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_imageRobot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imageRobot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetting = lv_imgbtn_create(ui_MainScreen);
    lv_imgbtn_set_src(ui_btnSetting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_settings48px_png, NULL);
    lv_obj_set_width(ui_btnSetting, 48);
    lv_obj_set_height(ui_btnSetting, 48);
    lv_obj_set_x(ui_btnSetting, 55);
    lv_obj_set_y(ui_btnSetting, 70);
    lv_obj_set_align(ui_btnSetting, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetting, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnSetting, &ui_img_settings48px_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifi = lv_imgbtn_create(ui_MainScreen);
    lv_imgbtn_set_src(ui_btnWifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi48px_png, NULL);
    lv_obj_set_width(ui_btnWifi, 48);
    lv_obj_set_height(ui_btnWifi, 48);
    lv_obj_set_x(ui_btnWifi, 120);
    lv_obj_set_y(ui_btnWifi, 70);
    lv_obj_set_align(ui_btnWifi, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnWifi, &ui_img_wifi48px_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_disableWifi = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_disableWifi, &ui_img_nowifi_14x10_png);
    lv_obj_set_width(ui_disableWifi, 14);
    lv_obj_set_height(ui_disableWifi, 10);
    lv_obj_set_x(ui_disableWifi, 146);
    lv_obj_set_y(ui_disableWifi, -110);
    lv_obj_set_align(ui_disableWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_disableWifi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_disableWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_enableWifi = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_enableWifi, &ui_img_wifi_14x8_png);
    lv_obj_set_width(ui_enableWifi, 14);
    lv_obj_set_height(ui_enableWifi, 8);
    lv_obj_set_x(ui_enableWifi, 147);
    lv_obj_set_y(ui_enableWifi, -110);
    lv_obj_set_align(ui_enableWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_enableWifi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_enableWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnSetting, ui_event_btnSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifi, ui_event_btnWifi, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_labelTime = NULL;
    ui_calendarMonth = NULL;
    ui_labelDate = NULL;
    ui_robotFaceArea = NULL;
    ui_imageRobot = NULL;
    ui_btnSetting = NULL;
    ui_btnWifi = NULL;
    ui_disableWifi = NULL;
    ui_enableWifi = NULL;

}
