// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_labelTime;
extern lv_obj_t * ui_calendarMonth;
extern lv_obj_t * ui_labelDate;
extern lv_obj_t * ui_robotFaceArea;
extern lv_obj_t * ui_imageRobot;
extern void ui_event_btnSetting(lv_event_t * e);
extern lv_obj_t * ui_btnSetting;
extern void ui_event_btnWifi(lv_event_t * e);
extern lv_obj_t * ui_btnWifi;
extern lv_obj_t * ui_disableWifi;
extern lv_obj_t * ui_enableWifi;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

