// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef UI_SYSTEMSCREEN_H
#define UI_SYSTEMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SystemScreen
extern void ui_SystemScreen_screen_init(void);
extern void ui_SystemScreen_screen_destroy(void);
extern lv_obj_t * ui_SystemScreen;
extern void ui_event_backHome2(lv_event_t * e);
extern lv_obj_t * ui_backHome2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_tempValue;
extern lv_obj_t * ui_cpu;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_cpuValue;
extern lv_obj_t * ui_ram;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_ramValue;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_chipModel;
extern lv_obj_t * ui_cpuFreq;
extern lv_obj_t * ui_flashSize;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

