// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScreen
extern void ui_SettingScreen_screen_init(void);
extern void ui_SettingScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_ssid;
extern lv_obj_t * ui_ipDevice;
extern lv_obj_t * ui_mac;
extern void ui_event_backHome1(lv_event_t * e);
extern lv_obj_t * ui_backHome1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_btnShutdown;
extern void ui_event_system(lv_event_t * e);
extern lv_obj_t * ui_system;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern void ui_event_weather(lv_event_t * e);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_ipPublic;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

