// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#include "ui.h"

lv_obj_t * ui_WifiSelectScreen;
lv_obj_t * ui_labelWifiTitle;
lv_obj_t * ui_containerWifiList;
lv_obj_t * ui_backHome;
lv_obj_t * ui_Label7;
lv_obj_t * ui_scanWifi;
lv_obj_t * ui_Label4;
lv_obj_t * ui_loadWifi;

// event funtions
void ui_event_backHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_OVER_RIGHT, 50, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_WifiSelectScreen_screen_init(void)
{
    ui_WifiSelectScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiSelectScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiSelectScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSelectScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelWifiTitle = lv_label_create(ui_WifiSelectScreen);
    lv_obj_set_width(ui_labelWifiTitle, 100);
    lv_obj_set_height(ui_labelWifiTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelWifiTitle, -6);
    lv_obj_set_y(ui_labelWifiTitle, -102);
    lv_obj_set_align(ui_labelWifiTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelWifiTitle, "Wifi");
    lv_obj_set_style_text_color(ui_labelWifiTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelWifiTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelWifiTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelWifiTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_containerWifiList = lv_obj_create(ui_WifiSelectScreen);
    lv_obj_remove_style_all(ui_containerWifiList);
    lv_obj_set_width(ui_containerWifiList, 275);
    lv_obj_set_height(ui_containerWifiList, 183);
    lv_obj_set_x(ui_containerWifiList, 24);
    lv_obj_set_y(ui_containerWifiList, -22);
    lv_obj_set_align(ui_containerWifiList, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_containerWifiList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_containerWifiList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_containerWifiList, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_snap_x(ui_containerWifiList, LV_SCROLL_SNAP_START);
    lv_obj_set_style_border_width(ui_containerWifiList, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_containerWifiList, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_containerWifiList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_containerWifiList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_containerWifiList, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_containerWifiList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_containerWifiList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backHome = lv_btn_create(ui_WifiSelectScreen);
    lv_obj_set_width(ui_backHome, 69);
    lv_obj_set_height(ui_backHome, 21);
    lv_obj_set_x(ui_backHome, -113);
    lv_obj_set_y(ui_backHome, -103);
    lv_obj_set_align(ui_backHome, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_backHome, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_backHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_backHome, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_backHome);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Home");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scanWifi = lv_btn_create(ui_WifiSelectScreen);
    lv_obj_set_width(ui_scanWifi, 69);
    lv_obj_set_height(ui_scanWifi, 21);
    lv_obj_set_x(ui_scanWifi, 110);
    lv_obj_set_y(ui_scanWifi, -104);
    lv_obj_set_align(ui_scanWifi, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_scanWifi, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scanWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scanWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_scanWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scanWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scanWifi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_scanWifi);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Scan");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadWifi = lv_spinner_create(ui_WifiSelectScreen, 1000, 90);
    lv_obj_set_width(ui_loadWifi, 80);
    lv_obj_set_height(ui_loadWifi, 80);
    lv_obj_set_x(ui_loadWifi, -4);
    lv_obj_set_y(ui_loadWifi, -1);
    lv_obj_set_align(ui_loadWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loadWifi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_loadWifi, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_loadWifi, lv_color_hex(0x00FF2F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_loadWifi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backHome, ui_event_backHome, LV_EVENT_ALL, NULL);

}

void ui_WifiSelectScreen_screen_destroy(void)
{
    if(ui_WifiSelectScreen) lv_obj_del(ui_WifiSelectScreen);

    // NULL screen variables
    ui_WifiSelectScreen = NULL;
    ui_labelWifiTitle = NULL;
    ui_containerWifiList = NULL;
    ui_backHome = NULL;
    ui_Label7 = NULL;
    ui_scanWifi = NULL;
    ui_Label4 = NULL;
    ui_loadWifi = NULL;

}
