// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef UI_WEATHERSCREEN_H
#define UI_WEATHERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeatherScreen
extern void ui_WeatherScreen_screen_init(void);
extern void ui_WeatherScreen_screen_destroy(void);
extern void ui_event_WeatherScreen(lv_event_t * e);
extern lv_obj_t * ui_WeatherScreen;
extern lv_obj_t * ui_panelTemp;
extern lv_obj_t * ui_iconTemp;
extern lv_obj_t * ui_iconMax;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_feelsLike;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_iconMin;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_tempMax;
extern lv_obj_t * ui_tempMin;
extern lv_obj_t * ui_panelHumd;
extern lv_obj_t * ui_iconHumd;
extern lv_obj_t * ui_iconPress;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_wind;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_iconVisi;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_pressure;
extern lv_obj_t * ui_visibility;
extern lv_obj_t * ui_iconWind;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_infoData;
extern lv_obj_t * ui_panelMain;
extern lv_obj_t * ui_city;
extern lv_obj_t * ui_labelTime1;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_labelDate1;
extern lv_obj_t * ui_weatherMain;
extern lv_obj_t * ui_weatherDes;
extern lv_obj_t * ui_weatherIcon;
extern lv_obj_t * ui_icon10n72p;
extern lv_obj_t * ui_icon01d72p;
extern lv_obj_t * ui_icon50d50n72p;
extern lv_obj_t * ui_icon11d11n72p;
extern lv_obj_t * ui_icon13d13n72p;
extern lv_obj_t * ui_icon10d72p;
extern lv_obj_t * ui_icon09d09n72p;
extern lv_obj_t * ui_icon04d04n72p;
extern lv_obj_t * ui_icon03d03n72p;
extern lv_obj_t * ui_icon02n72p;
extern lv_obj_t * ui_icon02d72p;
extern lv_obj_t * ui_icon01n72p;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

