// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef UI_WIFISELECTSCREEN_H
#define UI_WIFISELECTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiSelectScreen
extern void ui_WifiSelectScreen_screen_init(void);
extern void ui_WifiSelectScreen_screen_destroy(void);
extern lv_obj_t * ui_WifiSelectScreen;
extern lv_obj_t * ui_labelWifiTitle;
extern lv_obj_t * ui_containerWifiList;
extern void ui_event_backHome(lv_event_t * e);
extern lv_obj_t * ui_backHome;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_scanWifi;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_loadWifi;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

