// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#ifndef UI_WIFIPASSWORDSCREEN_H
#define UI_WIFIPASSWORDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiPasswordScreen
extern void ui_WifiPasswordScreen_screen_init(void);
extern void ui_WifiPasswordScreen_screen_destroy(void);
extern void ui_event_WifiPasswordScreen(lv_event_t * e);
extern lv_obj_t * ui_WifiPasswordScreen;
extern lv_obj_t * ui_ssidTitle;
extern lv_obj_t * ui_ssidName;
extern lv_obj_t * ui_passTitle;
extern lv_obj_t * ui_keyboard;
extern void ui_event_passValue(lv_event_t * e);
extern lv_obj_t * ui_passValue;
extern lv_obj_t * ui_loadConnectWifi;
extern lv_obj_t * ui_backCorrect;
extern lv_obj_t * ui_correct;
extern lv_obj_t * ui_backIncorrect;
extern lv_obj_t * ui_incorrect;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

