// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#include "ui.h"

lv_obj_t * ui_WifiPasswordScreen;
lv_obj_t * ui_ssidTitle;
lv_obj_t * ui_ssidName;
lv_obj_t * ui_passTitle;
lv_obj_t * ui_keyboard;
lv_obj_t * ui_passValue;
lv_obj_t * ui_loadConnectWifi;
lv_obj_t * ui_backCorrect;
lv_obj_t * ui_correct;
lv_obj_t * ui_backIncorrect;
lv_obj_t * ui_incorrect;

// event funtions
void ui_event_WifiPasswordScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_WifiSelectScreen, LV_SCR_LOAD_ANIM_OVER_RIGHT, 50, 0, &ui_WifiSelectScreen_screen_init);
    }
}

void ui_event_passValue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_keyboard,  ui_passValue);
    }
}

// build funtions

void ui_WifiPasswordScreen_screen_init(void)
{
    ui_WifiPasswordScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiPasswordScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiPasswordScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPasswordScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssidTitle = lv_label_create(ui_WifiPasswordScreen);
    lv_obj_set_width(ui_ssidTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssidTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssidTitle, -122);
    lv_obj_set_y(ui_ssidTitle, -100);
    lv_obj_set_align(ui_ssidTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssidTitle, "SSID: ");
    lv_obj_set_style_text_color(ui_ssidTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssidTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssidTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssidName = lv_label_create(ui_WifiPasswordScreen);
    lv_obj_set_width(ui_ssidName, 200);
    lv_obj_set_height(ui_ssidName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssidName, 25);
    lv_obj_set_y(ui_ssidName, -100);
    lv_obj_set_align(ui_ssidName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssidName, "Wifi Name");
    lv_obj_set_style_text_color(ui_ssidName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssidName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ssidName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssidName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passTitle = lv_label_create(ui_WifiPasswordScreen);
    lv_obj_set_width(ui_passTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_passTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_passTitle, -104);
    lv_obj_set_y(ui_passTitle, -64);
    lv_obj_set_align(ui_passTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_passTitle, "Password:");
    lv_obj_set_style_text_color(ui_passTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_passTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_passTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_passTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keyboard = lv_keyboard_create(ui_WifiPasswordScreen);
    lv_obj_set_width(ui_keyboard, 315);
    lv_obj_set_height(ui_keyboard, 135);
    lv_obj_set_x(ui_keyboard, -1);
    lv_obj_set_y(ui_keyboard, 49);
    lv_obj_set_align(ui_keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_keyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passValue = lv_textarea_create(ui_WifiPasswordScreen);
    lv_obj_set_width(ui_passValue, 197);
    lv_obj_set_height(ui_passValue, 42);
    lv_obj_set_x(ui_passValue, 48);
    lv_obj_set_y(ui_passValue, -63);
    lv_obj_set_align(ui_passValue, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passValue, "Placeholder...");
    lv_obj_set_style_text_color(ui_passValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_passValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_passValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_passValue, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_passValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_passValue, lv_color_hex(0x030303), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_passValue, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_loadConnectWifi = lv_spinner_create(ui_WifiPasswordScreen, 1000, 90);
    lv_obj_set_width(ui_loadConnectWifi, 316);
    lv_obj_set_height(ui_loadConnectWifi, 235);
    lv_obj_set_x(ui_loadConnectWifi, 0);
    lv_obj_set_y(ui_loadConnectWifi, -1);
    lv_obj_set_align(ui_loadConnectWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loadConnectWifi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_loadConnectWifi, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loadConnectWifi, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadConnectWifi, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_loadConnectWifi, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_loadConnectWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_loadConnectWifi, 105, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_loadConnectWifi, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_loadConnectWifi, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_loadConnectWifi, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_loadConnectWifi, lv_color_hex(0x2DE04E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_loadConnectWifi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_backCorrect = lv_obj_create(ui_WifiPasswordScreen);
    lv_obj_remove_style_all(ui_backCorrect);
    lv_obj_set_width(ui_backCorrect, 314);
    lv_obj_set_height(ui_backCorrect, 236);
    lv_obj_set_align(ui_backCorrect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backCorrect, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_backCorrect, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backCorrect, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backCorrect, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_correct = lv_img_create(ui_backCorrect);
    lv_img_set_src(ui_correct, &ui_img_correct128px_png);
    lv_obj_set_width(ui_correct, 128);
    lv_obj_set_height(ui_correct, 128);
    lv_obj_set_x(ui_correct, 2);
    lv_obj_set_y(ui_correct, -5);
    lv_obj_set_align(ui_correct, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_correct, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_correct, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_correct, lv_color_hex(0x00E406), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_correct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backIncorrect = lv_obj_create(ui_WifiPasswordScreen);
    lv_obj_remove_style_all(ui_backIncorrect);
    lv_obj_set_width(ui_backIncorrect, 314);
    lv_obj_set_height(ui_backIncorrect, 236);
    lv_obj_set_align(ui_backIncorrect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backIncorrect, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_backIncorrect, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backIncorrect, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backIncorrect, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_incorrect = lv_img_create(ui_backIncorrect);
    lv_img_set_src(ui_incorrect, &ui_img_incorrect128px_png);
    lv_obj_set_width(ui_incorrect, 128);
    lv_obj_set_height(ui_incorrect, 128);
    lv_obj_set_x(ui_incorrect, 2);
    lv_obj_set_y(ui_incorrect, -5);
    lv_obj_set_align(ui_incorrect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_incorrect, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_incorrect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_incorrect, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_incorrect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_passValue, ui_event_passValue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiPasswordScreen, ui_event_WifiPasswordScreen, LV_EVENT_ALL, NULL);

}

void ui_WifiPasswordScreen_screen_destroy(void)
{
    if(ui_WifiPasswordScreen) lv_obj_del(ui_WifiPasswordScreen);

    // NULL screen variables
    ui_WifiPasswordScreen = NULL;
    ui_ssidTitle = NULL;
    ui_ssidName = NULL;
    ui_passTitle = NULL;
    ui_keyboard = NULL;
    ui_passValue = NULL;
    ui_loadConnectWifi = NULL;
    ui_backCorrect = NULL;
    ui_correct = NULL;
    ui_backIncorrect = NULL;
    ui_incorrect = NULL;

}
