// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32-2432S028R

#include "ui.h"

lv_obj_t * ui_WeatherScreen;
lv_obj_t * ui_panelTemp;
lv_obj_t * ui_iconTemp;
lv_obj_t * ui_iconMax;
lv_obj_t * ui_temperature;
lv_obj_t * ui_feelsLike;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label17;
lv_obj_t * ui_iconMin;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_tempMax;
lv_obj_t * ui_tempMin;
lv_obj_t * ui_panelHumd;
lv_obj_t * ui_iconHumd;
lv_obj_t * ui_iconPress;
lv_obj_t * ui_humidity;
lv_obj_t * ui_wind;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_iconVisi;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
lv_obj_t * ui_pressure;
lv_obj_t * ui_visibility;
lv_obj_t * ui_iconWind;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_infoData;
lv_obj_t * ui_panelMain;
lv_obj_t * ui_city;
lv_obj_t * ui_labelTime1;
lv_obj_t * ui_Image5;
lv_obj_t * ui_labelDate1;
lv_obj_t * ui_weatherMain;
lv_obj_t * ui_weatherDes;
lv_obj_t * ui_weatherIcon;
lv_obj_t * ui_icon10n72p;
lv_obj_t * ui_icon01d72p;
lv_obj_t * ui_icon50d50n72p;
lv_obj_t * ui_icon11d11n72p;
lv_obj_t * ui_icon13d13n72p;
lv_obj_t * ui_icon10d72p;
lv_obj_t * ui_icon09d09n72p;
lv_obj_t * ui_icon04d04n72p;
lv_obj_t * ui_icon03d03n72p;
lv_obj_t * ui_icon02n72p;
lv_obj_t * ui_icon02d72p;
lv_obj_t * ui_icon01n72p;

// event funtions
void ui_event_WeatherScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 50, 0, &ui_SettingScreen_screen_init);
    }
}

// build funtions

void ui_WeatherScreen_screen_init(void)
{
    ui_WeatherScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelTemp = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_panelTemp);
    lv_obj_set_width(ui_panelTemp, 152);
    lv_obj_set_height(ui_panelTemp, 87);
    lv_obj_set_x(ui_panelTemp, -79);
    lv_obj_set_y(ui_panelTemp, 42);
    lv_obj_set_align(ui_panelTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelTemp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTemp, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconTemp = lv_img_create(ui_panelTemp);
    lv_img_set_src(ui_iconTemp, &ui_img_icon_temp_22p_png);
    lv_obj_set_width(ui_iconTemp, 15);
    lv_obj_set_height(ui_iconTemp, 22);
    lv_obj_set_x(ui_iconTemp, -63);
    lv_obj_set_y(ui_iconTemp, -23);
    lv_obj_set_align(ui_iconTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_iconMax = lv_img_create(ui_panelTemp);
    lv_img_set_src(ui_iconMax, &ui_img_icon_max_11p_png);
    lv_obj_set_width(ui_iconMax, 11);
    lv_obj_set_height(ui_iconMax, 11);
    lv_obj_set_x(ui_iconMax, -65);
    lv_obj_set_y(ui_iconMax, 17);
    lv_obj_set_align(ui_iconMax, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconMax, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconMax, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperature = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_temperature, 100);
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, 0);
    lv_obj_set_y(ui_temperature, -25);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "---°C");
    lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temperature, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feelsLike = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_feelsLike, 50);
    lv_obj_set_height(ui_feelsLike, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_feelsLike, 47);
    lv_obj_set_y(ui_feelsLike, 0);
    lv_obj_set_align(ui_feelsLike, LV_ALIGN_CENTER);
    lv_label_set_text(ui_feelsLike, "---°C");
    lv_obj_set_style_text_color(ui_feelsLike, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_feelsLike, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_feelsLike, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_feelsLike, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -45);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Feels like");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -43);
    lv_obj_set_y(ui_Label17, 17);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Max");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconMin = lv_img_create(ui_panelTemp);
    lv_img_set_src(ui_iconMin, &ui_img_icon_min_11p_png);
    lv_obj_set_width(ui_iconMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconMin, -65);
    lv_obj_set_y(ui_iconMin, 34);
    lv_obj_set_align(ui_iconMin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconMin, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconMin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -44);
    lv_obj_set_y(ui_Label18, 34);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Min");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -11);
    lv_obj_set_y(ui_Label19, -1);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, ":");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -21);
    lv_obj_set_y(ui_Label20, 17);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, ":");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -21);
    lv_obj_set_y(ui_Label21, 34);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, ":");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempMax = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_tempMax, 50);
    lv_obj_set_height(ui_tempMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempMax, 47);
    lv_obj_set_y(ui_tempMax, 17);
    lv_obj_set_align(ui_tempMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempMax, "---°C");
    lv_obj_set_style_text_color(ui_tempMax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempMax, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempMax, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempMin = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_tempMin, 50);
    lv_obj_set_height(ui_tempMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempMin, 47);
    lv_obj_set_y(ui_tempMin, 34);
    lv_obj_set_align(ui_tempMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempMin, "---°C");
    lv_obj_set_style_text_color(ui_tempMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempMin, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempMin, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelHumd = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_panelHumd);
    lv_obj_set_width(ui_panelHumd, 152);
    lv_obj_set_height(ui_panelHumd, 87);
    lv_obj_set_x(ui_panelHumd, 79);
    lv_obj_set_y(ui_panelHumd, 42);
    lv_obj_set_align(ui_panelHumd, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelHumd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelHumd, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelHumd, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHumd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconHumd = lv_img_create(ui_panelHumd);
    lv_img_set_src(ui_iconHumd, &ui_img_icon_humd_22p_png);
    lv_obj_set_width(ui_iconHumd, 15);
    lv_obj_set_height(ui_iconHumd, 22);
    lv_obj_set_x(ui_iconHumd, -63);
    lv_obj_set_y(ui_iconHumd, -23);
    lv_obj_set_align(ui_iconHumd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconHumd, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconHumd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_iconPress = lv_img_create(ui_panelHumd);
    lv_img_set_src(ui_iconPress, &ui_img_icon_pressure_11p_png);
    lv_obj_set_width(ui_iconPress, 11);
    lv_obj_set_height(ui_iconPress, 11);
    lv_obj_set_x(ui_iconPress, -65);
    lv_obj_set_y(ui_iconPress, 17);
    lv_obj_set_align(ui_iconPress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconPress, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconPress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humidity = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_humidity, 100);
    lv_obj_set_height(ui_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity, 0);
    lv_obj_set_y(ui_humidity, -25);
    lv_obj_set_align(ui_humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity, "---%");
    lv_obj_set_style_text_color(ui_humidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humidity, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidity, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wind = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_wind, 70);
    lv_obj_set_height(ui_wind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wind, 36);
    lv_obj_set_y(ui_wind, 0);
    lv_obj_set_align(ui_wind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wind, "---km/h");
    lv_obj_set_style_text_color(ui_wind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wind, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wind, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -40);
    lv_obj_set_y(ui_Label26, 0);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Wind");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -29);
    lv_obj_set_y(ui_Label27, 17);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Pressure");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconVisi = lv_img_create(ui_panelHumd);
    lv_img_set_src(ui_iconVisi, &ui_img_icon_visibility_11p_png);
    lv_obj_set_width(ui_iconVisi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconVisi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconVisi, -65);
    lv_obj_set_y(ui_iconVisi, 34);
    lv_obj_set_align(ui_iconVisi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconVisi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconVisi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -30);
    lv_obj_set_y(ui_Label28, 34);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Visibility");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -16);
    lv_obj_set_y(ui_Label29, -1);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, ":");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 3);
    lv_obj_set_y(ui_Label30, 17);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, ":");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 3);
    lv_obj_set_y(ui_Label31, 34);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, ":");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pressure = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_pressure, 60);
    lv_obj_set_height(ui_pressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pressure, 41);
    lv_obj_set_y(ui_pressure, 17);
    lv_obj_set_align(ui_pressure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pressure, "----hPa");
    lv_obj_set_style_text_color(ui_pressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pressure, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pressure, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_visibility = lv_label_create(ui_panelHumd);
    lv_obj_set_width(ui_visibility, 50);
    lv_obj_set_height(ui_visibility, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_visibility, 46);
    lv_obj_set_y(ui_visibility, 34);
    lv_obj_set_align(ui_visibility, LV_ALIGN_CENTER);
    lv_label_set_text(ui_visibility, "---km");
    lv_obj_set_style_text_color(ui_visibility, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_visibility, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_visibility, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_visibility, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconWind = lv_img_create(ui_panelHumd);
    lv_img_set_src(ui_iconWind, &ui_img_icon_wind_11p_png);
    lv_obj_set_width(ui_iconWind, 11);
    lv_obj_set_height(ui_iconWind, 11);
    lv_obj_set_x(ui_iconWind, -65);
    lv_obj_set_y(ui_iconWind, 0);
    lv_obj_set_align(ui_iconWind, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWind, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconWind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_WeatherScreen);
    lv_obj_set_width(ui_Panel1, 310);
    lv_obj_set_height(ui_Panel1, 22);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 102);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_infoData = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_infoData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_infoData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_infoData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_infoData, "Last data up date: 00:00:00 (Succeed");
    lv_obj_set_style_text_color(ui_infoData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_infoData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_infoData, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelMain = lv_obj_create(ui_WeatherScreen);
    lv_obj_set_width(ui_panelMain, 310);
    lv_obj_set_height(ui_panelMain, 110);
    lv_obj_set_x(ui_panelMain, 0);
    lv_obj_set_y(ui_panelMain, -61);
    lv_obj_set_align(ui_panelMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelMain, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelMain, lv_color_hex(0x262635), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_city = lv_label_create(ui_panelMain);
    lv_obj_set_width(ui_city, 80);
    lv_obj_set_height(ui_city, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_city, -90);
    lv_obj_set_y(ui_city, -44);
    lv_obj_set_align(ui_city, LV_ALIGN_CENTER);
    lv_label_set_text(ui_city, "Hanoi");
    lv_obj_set_style_text_color(ui_city, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_city, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_city, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_city, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTime1 = lv_label_create(ui_panelMain);
    lv_obj_set_width(ui_labelTime1, 200);
    lv_obj_set_height(ui_labelTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTime1, -48);
    lv_obj_set_y(ui_labelTime1, 0);
    lv_obj_set_align(ui_labelTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTime1, "--:--:--");
    lv_obj_set_style_text_color(ui_labelTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelTime1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTime1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_panelMain);
    lv_img_set_src(ui_Image5, &ui_img_icon_location_11p_png);
    lv_obj_set_width(ui_Image5, 11);
    lv_obj_set_height(ui_Image5, 11);
    lv_obj_set_x(ui_Image5, -143);
    lv_obj_set_y(ui_Image5, -44);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelDate1 = lv_label_create(ui_panelMain);
    lv_obj_set_width(ui_labelDate1, 160);
    lv_obj_set_height(ui_labelDate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDate1, -66);
    lv_obj_set_y(ui_labelDate1, 38);
    lv_obj_set_align(ui_labelDate1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDate1, "---, --/--/----");
    lv_obj_set_style_text_color(ui_labelDate1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDate1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelDate1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDate1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherMain = lv_label_create(ui_panelMain);
    lv_obj_set_width(ui_weatherMain, 72);
    lv_obj_set_height(ui_weatherMain, 15);
    lv_obj_set_x(ui_weatherMain, 104);
    lv_obj_set_y(ui_weatherMain, -45);
    lv_obj_set_align(ui_weatherMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherMain, "Clear");
    lv_obj_set_style_text_color(ui_weatherMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_weatherMain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherMain, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherDes = lv_label_create(ui_panelMain);
    lv_obj_set_width(ui_weatherDes, 72);
    lv_obj_set_height(ui_weatherDes, 15);
    lv_obj_set_x(ui_weatherDes, 104);
    lv_obj_set_y(ui_weatherDes, 45);
    lv_obj_set_align(ui_weatherDes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherDes, "Clear sky");
    lv_obj_set_style_text_color(ui_weatherDes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherDes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_weatherDes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherDes, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherIcon = lv_img_create(ui_panelMain);
    lv_obj_set_width(ui_weatherIcon, 72);
    lv_obj_set_height(ui_weatherIcon, 72);
    lv_obj_set_x(ui_weatherIcon, 104);
    lv_obj_set_y(ui_weatherIcon, 0);
    lv_obj_set_align(ui_weatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weatherIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_weatherIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon10n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon10n72p, &ui_img_icon_10n_72p_png);
    lv_obj_set_width(ui_icon10n72p, 72);
    lv_obj_set_height(ui_icon10n72p, 72);
    lv_obj_set_align(ui_icon10n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon10n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon10n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon01d72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon01d72p, &ui_img_icon_01d_72p_png);
    lv_obj_set_width(ui_icon01d72p, 72);
    lv_obj_set_height(ui_icon01d72p, 72);
    lv_obj_set_align(ui_icon01d72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon01d72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon01d72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon50d50n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon50d50n72p, &ui_img_icon_50d_50n_72p_png);
    lv_obj_set_width(ui_icon50d50n72p, 72);
    lv_obj_set_height(ui_icon50d50n72p, 72);
    lv_obj_set_align(ui_icon50d50n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon50d50n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon50d50n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon11d11n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon11d11n72p, &ui_img_icon_11d_11n_72p_png);
    lv_obj_set_width(ui_icon11d11n72p, 72);
    lv_obj_set_height(ui_icon11d11n72p, 72);
    lv_obj_set_align(ui_icon11d11n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon11d11n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon11d11n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon13d13n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon13d13n72p, &ui_img_icon_13d_13n_72p_png);
    lv_obj_set_width(ui_icon13d13n72p, 72);
    lv_obj_set_height(ui_icon13d13n72p, 72);
    lv_obj_set_align(ui_icon13d13n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon13d13n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon13d13n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon10d72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon10d72p, &ui_img_icon_10d_72p_png);
    lv_obj_set_width(ui_icon10d72p, 72);
    lv_obj_set_height(ui_icon10d72p, 72);
    lv_obj_set_align(ui_icon10d72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon10d72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon10d72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon09d09n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon09d09n72p, &ui_img_icon_09d_09n_72p_png);
    lv_obj_set_width(ui_icon09d09n72p, 72);
    lv_obj_set_height(ui_icon09d09n72p, 72);
    lv_obj_set_align(ui_icon09d09n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon09d09n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon09d09n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon04d04n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon04d04n72p, &ui_img_icon_04d_04n_72p_png);
    lv_obj_set_width(ui_icon04d04n72p, 72);
    lv_obj_set_height(ui_icon04d04n72p, 72);
    lv_obj_set_align(ui_icon04d04n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon04d04n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon04d04n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon03d03n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon03d03n72p, &ui_img_icon_03d_03n_72p_png);
    lv_obj_set_width(ui_icon03d03n72p, 72);
    lv_obj_set_height(ui_icon03d03n72p, 72);
    lv_obj_set_align(ui_icon03d03n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon03d03n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon03d03n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon02n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon02n72p, &ui_img_icon_02n_72p_png);
    lv_obj_set_width(ui_icon02n72p, 72);
    lv_obj_set_height(ui_icon02n72p, 72);
    lv_obj_set_align(ui_icon02n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon02n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon02n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon02d72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon02d72p, &ui_img_icon_02d_72p_png);
    lv_obj_set_width(ui_icon02d72p, 72);
    lv_obj_set_height(ui_icon02d72p, 72);
    lv_obj_set_align(ui_icon02d72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon02d72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon02d72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon01n72p = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_icon01n72p, &ui_img_icon_01n_72p_png);
    lv_obj_set_width(ui_icon01n72p, 72);
    lv_obj_set_height(ui_icon01n72p, 72);
    lv_obj_set_align(ui_icon01n72p, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_icon01n72p, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon01n72p, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_WeatherScreen, ui_event_WeatherScreen, LV_EVENT_ALL, NULL);

}

void ui_WeatherScreen_screen_destroy(void)
{
    if(ui_WeatherScreen) lv_obj_del(ui_WeatherScreen);

    // NULL screen variables
    ui_WeatherScreen = NULL;
    ui_panelTemp = NULL;
    ui_iconTemp = NULL;
    ui_iconMax = NULL;
    ui_temperature = NULL;
    ui_feelsLike = NULL;
    ui_Label15 = NULL;
    ui_Label17 = NULL;
    ui_iconMin = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_tempMax = NULL;
    ui_tempMin = NULL;
    ui_panelHumd = NULL;
    ui_iconHumd = NULL;
    ui_iconPress = NULL;
    ui_humidity = NULL;
    ui_wind = NULL;
    ui_Label26 = NULL;
    ui_Label27 = NULL;
    ui_iconVisi = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;
    ui_Label30 = NULL;
    ui_Label31 = NULL;
    ui_pressure = NULL;
    ui_visibility = NULL;
    ui_iconWind = NULL;
    ui_Panel1 = NULL;
    ui_infoData = NULL;
    ui_panelMain = NULL;
    ui_city = NULL;
    ui_labelTime1 = NULL;
    ui_Image5 = NULL;
    ui_labelDate1 = NULL;
    ui_weatherMain = NULL;
    ui_weatherDes = NULL;
    ui_weatherIcon = NULL;
    ui_icon10n72p = NULL;
    ui_icon01d72p = NULL;
    ui_icon50d50n72p = NULL;
    ui_icon11d11n72p = NULL;
    ui_icon13d13n72p = NULL;
    ui_icon10d72p = NULL;
    ui_icon09d09n72p = NULL;
    ui_icon04d04n72p = NULL;
    ui_icon03d03n72p = NULL;
    ui_icon02n72p = NULL;
    ui_icon02d72p = NULL;
    ui_icon01n72p = NULL;

}
